# Generated by Django 4.2.3 on 2023-07-14 15:31

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BillPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
                ('due_date', models.DateField(blank=True)),
                ('unique', models.BooleanField(default=True)),
                ('artifact', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/files/artifacts/'), upload_to='')),
                ('quantity', models.IntegerField(default=1)),
                ('obs', models.TextField(blank=True)),
                ('frequency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bill.billfrequency')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bill.billpriority')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bill.billtype')),
            ],
        ),
    ]
