# Generated by Django 4.2.3 on 2023-11-15 20:26

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='artifact',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='files/artifacts/'), upload_to=''),
        ),
    ]
