# Generated by Django 4.2.3 on 2023-11-15 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('actual_limit', models.DecimalField(decimal_places=2, max_digits=100)),
                ('due_date', models.DateField(blank=True)),
                ('obs', models.TextField(blank=True)),
                ('final_number', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='credit_card.creditcardoperator')),
            ],
        ),
    ]
