# Generated by Django 4.2.3 on 2023-11-15 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='due_date',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='due_day',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31)]),
            preserve_default=False,
        ),
    ]
