# Generated by Django 4.2.3 on 2023-11-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card', '0003_creditcard_limit_avaliable'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
    ]
